[2024-01-04T13:43:27.974+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: snow_dag.is_snow_api_ready manual__2024-01-04T13:40:38.001998+00:00 [queued]>
[2024-01-04T13:43:28.017+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: snow_dag.is_snow_api_ready manual__2024-01-04T13:40:38.001998+00:00 [queued]>
[2024-01-04T13:43:28.017+0000] {taskinstance.py:2171} INFO - Starting attempt 3 of 4
[2024-01-04T13:43:28.113+0000] {taskinstance.py:2192} INFO - Executing <Task(HttpSensor): is_snow_api_ready> on 2024-01-04 13:40:38.001998+00:00
[2024-01-04T13:43:28.117+0000] {standard_task_runner.py:60} INFO - Started process 559 to run task
[2024-01-04T13:43:28.120+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'snow_dag', 'is_snow_api_ready', 'manual__2024-01-04T13:40:38.001998+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/servicenow_dag.py', '--cfg-path', '/tmp/tmp9wov57x8']
[2024-01-04T13:43:28.123+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask is_snow_api_ready
[2024-01-04T13:43:28.272+0000] {task_command.py:423} INFO - Running <TaskInstance: snow_dag.is_snow_api_ready manual__2024-01-04T13:40:38.001998+00:00 [running]> on host 4a92eecc6669
[2024-01-04T13:43:28.430+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='prady1900' AIRFLOW_CTX_DAG_ID='snow_dag' AIRFLOW_CTX_TASK_ID='is_snow_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T13:40:38.001998+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-04T13:40:38.001998+00:00'
[2024-01-04T13:43:28.431+0000] {http.py:130} INFO - Poking: api/now/table/incident
[2024-01-04T13:43:28.457+0000] {base.py:83} INFO - Using connection ID 'snow_api_id' for task execution.
[2024-01-04T13:43:30.758+0000] {base.py:293} INFO - Success criteria met. Exiting.
[2024-01-04T13:43:30.768+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=snow_dag, task_id=is_snow_api_ready, execution_date=20240104T134038, start_date=20240104T134327, end_date=20240104T134330
[2024-01-04T13:43:30.866+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-04T13:43:30.906+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
