[2024-01-04T07:06:23.914+0000] {taskinstance.py:1947} INFO - Dependencies not met for <TaskInstance: db_dg.create_post_DB manual__2024-01-04T07:00:44.090125+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2024-01-04T07:06:23.918+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2024-01-04T07:12:52.668+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: db_dg.create_post_DB manual__2024-01-04T07:00:44.090125+00:00 [queued]>
[2024-01-04T07:12:52.677+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: db_dg.create_post_DB manual__2024-01-04T07:00:44.090125+00:00 [queued]>
[2024-01-04T07:12:52.678+0000] {taskinstance.py:2171} INFO - Starting attempt 3 of 5
[2024-01-04T07:12:52.806+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): create_post_DB> on 2024-01-04 07:00:44.090125+00:00
[2024-01-04T07:12:52.821+0000] {standard_task_runner.py:60} INFO - Started process 548 to run task
[2024-01-04T07:12:52.828+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'db_dg', 'create_post_DB', 'manual__2024-01-04T07:00:44.090125+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/create_database_dag.py', '--cfg-path', '/tmp/tmpiqr54278']
[2024-01-04T07:12:52.832+0000] {standard_task_runner.py:88} INFO - Job 67: Subtask create_post_DB
[2024-01-04T07:12:52.989+0000] {task_command.py:423} INFO - Running <TaskInstance: db_dg.create_post_DB manual__2024-01-04T07:00:44.090125+00:00 [running]> on host 34fb0f920c20
[2024-01-04T07:12:53.308+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='prady1900' AIRFLOW_CTX_DAG_ID='db_dg' AIRFLOW_CTX_TASK_ID='create_post_DB' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T07:00:44.090125+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-04T07:00:44.090125+00:00'
[2024-01-04T07:12:53.309+0000] {sql.py:276} INFO - Executing: 
create table if not exists incident_new(
    id integer ,
    impact integer,
    number varchar(50),
    primary key(id)
)
[2024-01-04T07:12:53.319+0000] {base.py:83} INFO - Using connection ID 'postgres_connect' for task execution.
[2024-01-04T07:12:53.391+0000] {base.py:83} INFO - Using connection ID 'postgres_connect' for task execution.
[2024-01-04T07:12:53.399+0000] {sql.py:432} INFO - Running statement: 
create table if not exists incident_new(
    id integer ,
    impact integer,
    number varchar(50),
    primary key(id)
), parameters: None
[2024-01-04T07:12:53.410+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=db_dg, task_id=create_post_DB, execution_date=20240104T070044, start_date=20240104T071252, end_date=20240104T071253
[2024-01-04T07:12:53.524+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-04T07:12:53.552+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
